### ISSUE TITLE
can not install success

### ISSUE THREAD

**Issue by isfong** [sclausen/ngx-mqtt#130]
- [ ] **I have searched for similar issues in this repository, but couldn't find one.**
- [ ] **I have read the README and have a basic understanding how angular works.**
## I'm submitting a... can not install success, this is my error logs 
```error-logs
fong@isfong:/home/fong
[2019-03-21T06_12_16_729Z-debug.log](https://github.com/sclausen/ngx-mqtt/files/2991014/2019-03-21T06_12_16_729Z-debug.log)
/WebStormProjects/ng-bossdream-latest$ npm install ngx-mqtt --save
npm ERR! prepareGitDep 1> 
npm ERR! prepareGitDep > pre-commit@1.2.2 install /home/fong/.npm/_cacache/tmp/git-clone-ad67f7ee/node_modules/pre-commit
npm ERR! prepareGitDep > node install.js
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 
npm ERR! prepareGitDep > spawn-sync@1.0.15 postinstall /home/fong/.npm/_cacache/tmp/git-clone-ad67f7ee/node_modules/spawn-sync
npm ERR! prepareGitDep > node postinstall
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 
npm ERR! prepareGitDep > ngrok@2.1.8 postinstall /home/fong/.npm/_cacache/tmp/git-clone-ad67f7ee/node_modules/ngrok
npm ERR! prepareGitDep > node ./postinstall.js
npm ERR! prepareGitDep 
npm ERR! prepareGitDep ngrok - downloading binary https://bin.equinox.io/a/b87faFPKrii/ngrok-2.1.1-linux-amd64.tar.gz ...
npm ERR! prepareGitDep ngrok - binary downloaded...
npm ERR! prepareGitDep ngrok - binary unpacked.
npm ERR! prepareGitDep 
npm ERR! prepareGitDep > mqtt@2.18.8 prepare /home/fong/.npm/_cacache/tmp/git-clone-ad67f7ee
npm ERR! prepareGitDep > npm run browser-build
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 
npm ERR! prepareGitDep > mqtt@2.18.8 browser-build /home/fong/.npm/_cacache/tmp/git-clone-ad67f7ee
npm ERR! prepareGitDep > rimraf dist/ && mkdirp dist/ && browserify mqtt.js -s mqtt > dist/mqtt.js && uglifyjs < dist/mqtt.js > dist/mqtt.min.js
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
npm ERR! prepareGitDep npm WARN deprecated istanbul@0.4.5: This module is no longer maintained, try this instead:
npm ERR! prepareGitDep npm WARN deprecated   npm i nyc
npm ERR! prepareGitDep npm WARN deprecated Visit https://istanbul.js.org/integrations for other alternatives.
npm ERR! prepareGitDep npm WARN deprecated formatio@1.1.1: This package is unmaintained. Use @sinonjs/formatio instead
npm ERR! prepareGitDep npm WARN deprecated samsam@1.1.2: This package has been deprecated in favour of @sinonjs/samsam
npm ERR! prepareGitDep npm WARN deprecated samsam@1.1.3: This package has been deprecated in favour of @sinonjs/samsam
npm ERR! prepareGitDep npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! prepareGitDep npm WARN deprecated istanbul@0.2.16: This module is no longer maintained, try this instead:
npm ERR! prepareGitDep npm WARN deprecated   npm i nyc
npm ERR! prepareGitDep npm WARN deprecated Visit https://istanbul.js.org/integrations for other alternatives.
npm ERR! prepareGitDep npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm ERR! prepareGitDep npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar
npm ERR! prepareGitDep npm WARN deprecated connect@2.12.0: connect 2.x series is deprecated
npm ERR! prepareGitDep npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm ERR! prepareGitDep npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm ERR! prepareGitDep npm WARN deprecated minimatch@0.4.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! prepareGitDep npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! prepareGitDep npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm ERR! prepareGitDep npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! prepareGitDep npm WARN deprecated hoek@0.9.1: The major version is no longer supported. Please update to 4.x or newer
npm ERR! prepareGitDep npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! prepareGitDep Parse error at 0:9015,65
npm ERR! prepareGitDep             result += currentValue.reduce((currentLength, value) => {
npm ERR! prepareGitDep                                                                  ^
npm ERR! prepareGitDep ERROR: Invalid assignment
npm ERR! prepareGitDep     at JS_Parse_Error.get (eval at <anonymous> (/home/fong/.npm/_cacache/tmp/git-clone-ad67f7ee/node_modules/uglify-js/tools/node.js:20:1), <anonymous>:71:23)
npm ERR! prepareGitDep     at fatal (/home/fong/.npm/_cacache/tmp/git-clone-ad67f7ee/node_modules/uglify-js/bin/uglifyjs:296:53)
npm ERR! prepareGitDep     at run (/home/fong/.npm/_cacache/tmp/git-clone-ad67f7ee/node_modules/uglify-js/bin/uglifyjs:240:9)
npm ERR! prepareGitDep     at ReadStream.<anonymous> (/home/fong/.npm/_cacache/tmp/git-clone-ad67f7ee/node_modules/uglify-js/bin/uglifyjs:173:9)
npm ERR! prepareGitDep     at ReadStream.emit (events.js:194:15)
npm ERR! prepareGitDep     at endReadableNT (_stream_readable.js:1125:12)
npm ERR! prepareGitDep     at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 1
npm ERR! prepareGitDep npm ERR! mqtt@2.18.8 browser-build: `rimraf dist/ && mkdirp dist/ && browserify mqtt.js -s mqtt > dist/mqtt.js && uglifyjs < dist/mqtt.js > dist/mqtt.min.js`
npm ERR! prepareGitDep npm ERR! Exit status 1
npm ERR! prepareGitDep npm ERR! 
npm ERR! prepareGitDep npm ERR! Failed at the mqtt@2.18.8 browser-build script.
npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep 
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     /home/fong/.npm/_logs/2019-03-21T06_12_16_588Z-debug.log
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 1
npm ERR! prepareGitDep npm ERR! mqtt@2.18.8 prepare: `npm run browser-build`
npm ERR! prepareGitDep npm ERR! Exit status 1
npm ERR! prepareGitDep npm ERR! 
npm ERR! prepareGitDep npm ERR! Failed at the mqtt@2.18.8 prepare script.
npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep 
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     /home/fong/.npm/_logs/2019-03-21T06_12_16_620Z-debug.log
npm ERR! prepareGitDep 
npm ERR! premature close

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/fong/.npm/_logs/2019-03-21T06_12_16_729Z-debug.log

```

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report  
- [ ] Feature request

## Environment

<pre><code>
ngx-mqtt version: X.Y.Z

- Broker 

Others:

</code></pre>

**Comment by sclausen** [comment]
OS?
node version?
npm version?

**Comment by isfong** [comment]
> OS？
> 节点版本？
> npm版本？

#### OS: Ubuntu 18.04.2 LTS
#### node version: v10.15.3
#### npm version: 6.4.1
#### I directly to clone your project and then intend to release a package, but in your project cannot NPM install successful, my location is China, I also is to use the official image problem, but use to [alibaba mirror](http://npm.taobao.org/) is the same installation failure, is no solution, i need copy the package into my project node_modes and  run
### orig
```cmd
npm config set registry https://registry.npmjs.org/
```
### use alibaba taobao image
```cmd
npm config set registry http://registry.npm.taobao.org/
```

**Comment by sclausen** [comment]
Are you sure you‘re using node 10? The following error looks like node cant use es6 lambdas:
``` sh
npm ERR! prepareGitDep Parse error at 0:9015,65
npm ERR! prepareGitDep             result += currentValue.reduce((currentLength, value) => {
npm ERR! prepareGitDep
```

**Comment by sclausen** [comment]
Why didn‘t you tried to do `npm install ngx-mqtt` in the project folder where you want to use the library?

**Comment by david-jng** [comment]
Hey @sclausen,
I'm facing the same issue as @isfong . I attached the log file.
I tried `npm clean cache --force` and` npm i`.

Thanks in advance!

Angular CLI: 7.2.4
Node: 10.15.0
OS: win32 x64
Angular: 7.2.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.4
@angular-devkit/build-angular     0.12.4
@angular-devkit/build-optimizer   0.12.4
@angular-devkit/build-webpack     0.12.4
@angular-devkit/core              7.2.4
@angular-devkit/schematics        7.2.4
@ngtools/webpack                  7.2.4
@schematics/angular               7.2.4
@schematics/update                0.12.4
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.28.4

[2019-03-22T20_15_26_285Z-debug.log](https://github.com/sclausen/ngx-mqtt/files/2998144/2019-03-22T20_15_26_285Z-debug.log)

**Comment by sclausen** [comment]
@isfong @david-jng you both tried to install the cloned repository, not installing via `npm i ngx-mqtt` in a project, right?

**Comment by david-jng** [comment]
@sclausen I tried installing via `npm i ngx-mqtt` and `npm i ngx-mqtt --save`

**Comment by sclausen** [comment]
@david-jng your error is caused by the incompatibility of ngx-mqtt with windows together with npm. If you could use yarn to install the library, that would solve your issue.
I‘m not completly sure what @isfong tried to do though.

**Comment by isfong** [comment]
> @david-jng your error is caused by the incompatibility of ngx-mqtt with windows together with npm. If you could use yarn to install the library, that would solve your issue.
> I‘m not completly sure what @isfong tried to do though.

 the first run command npm install ngx-mqtt --save in my project, but there were no installation is successful, then take manually copy to solve

**Comment by isfong** [comment]
Seems to be due to your package depends on the mqtt.js, mqtt.js is unable to install a success, I'm not sure

**Comment by sclausen** [comment]
@isfong `mqtt.js` is bundled into the package you install with `npm i ngx-mqtt`, so there can't occur any error regarding `mqtt.js` when you execute `npm i ngx-mqtt`. Could you provide a logfile for this execution?

The error you got when executing `npm I` inside the cloned repository could be because of an old node version, since the error states your compiler doesn’t know what an es6 lambda is.

**Comment by isfong** [comment]
> @isfong `mqtt.js` is bundled into the package you install with `npm i ngx-mqtt`, so there can't occur any error regarding `mqtt.js` when you execute `npm i ngx-mqtt`. Could you provide a logfile for this execution?
> 
> The error you got when executing `npm i` inside the cloned repository could be because of an old node version, since the error states your compiler doesn’t know what an es6 lambda is.

I'm sure can use yarn installation is successful, thank you very much

**Comment by sclausen** [comment]
That’s great to hear!
