### ISSUE TITLE
Where to import NgxMqttServiceConfig from? NullInjectorError error in Angular tests

### ISSUE THREAD

**Issue by minicatsCB** [sclausen/ngx-mqtt#157]
- [x] **I have searched for similar issues in this repository, but couldn't find one.**
- [x] **I have read the README and have a basic understanding how angular works.**
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report  
- [ ] Feature request
- [x] Help wanted

## Current behavior
I'm developing an application with Angular 8 and ngx-mqtt. When I run the tests (the ones defined in `.spec.ts` files), I get this error:
```
NullInjectorError: StaticInjectorError(DynamicTestModule)[InjectionToken NgxMqttServiceConfig]: 
          StaticInjectorError(Platform: core)[InjectionToken NgxMqttServiceConfig]: 
            NullInjectorError: No provider for InjectionToken NgxMqttServiceConfig!
        error properties: Object({ ngTempTokenPath: null, ngTokenPath: [ InjectionToken NgxMqttServiceConfig ], ngDebugContext: DebugContext_({ view: Object({ def: Object({ factory: Function, nodeFlags: 33800193, rootNodeFlags: 33554433, nodeMatchedQueries: 0, flags: 0, nodes: [ Object({ nodeIndex: 0, parent: null, renderParent: null, bindingIndex: 0, outputIndex: 0, checkIndex: 0, flags: 33554433, childFlags: 245760, directChildFlags: 245760, childMatchedQueries: 0, matchedQueries: Object({  }), matchedQueryIds: 0, references: Object({  }), ngContentIndex: null, childCount: 1, bindings: [  ], bindingFlags: 0, outputs: [  ], element: Object({ ns: '', name: 'app-movies', attrs: [  ], template: null, componentProvider: Object({ nodeIndex: 1, parent: <circular reference: Object>, renderParent: <circular reference: Object>, bindingIndex: 0, outputIndex: 0, checkIndex: 1, flags: 245760, childFlags: 0, directChildFlags: 0, childMatchedQueries: 0, matchedQueries: Object, matchedQueryIds: 0, references: Object, ngC ...
            at <Jasmine>
            at NullInjector.get (http://localhost:9876/_karma_webpack_/vendor.js:40144:27)
            at resolveToken (http://localhost:9876/_karma_webpack_/vendor.js:55062:24)
            at tryResolveToken (http://localhost:9876/_karma_webpack_/vendor.js:54988:16)
            at StaticInjector.get (http://localhost:9876/_karma_webpack_/vendor.js:54838:20)
            at resolveToken (http://localhost:9876/_karma_webpack_/vendor.js:55062:24)
            at tryResolveToken (http://localhost:9876/_karma_webpack_/vendor.js:54988:16)
            at StaticInjector.get (http://localhost:9876/_karma_webpack_/vendor.js:54838:20)
            at resolveNgModuleDep (http://localhost:9876/_karma_webpack_/vendor.js:66025:29)
            at NgModuleRef_.get (http://localhost:9876/_karma_webpack_/vendor.js:67091:16)
            at injectInjectorOnly (http://localhost:9876/_karma_webpack_/vendor.js:40023:33)
        Error: Expected undefined to be truthy.
            at <Jasmine>
            at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/main.js:1731:27)
            at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/polyfills.js:3833:26)
            at ProxyZoneSpec.push../node_modules/zone.js/dist/zone-testing.js.ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/vendor.js:138795:39)
```

## Expected behavior
Not receive the `NullInjectorError`.

## Minimal reproduction of the problem with instructions
This is my current `.spec.ts` file:
```javascript
describe("MoviesComponent", () => {
    let component: MoviesComponent;
    let fixture: ComponentFixture<MoviesComponent>;

    FeveTestBed.prepare([MoviesComponent]);

    beforeEach(() => {
        fixture = TestBed.createComponent(MoviesComponent);
        component = fixture.componentInstance;
        fixture.detectChanges();
    });

    it("should create", () => {
        expect(component).toBeTruthy();  // <------- FAILS HERE
    });
});
```

In the `.component.ts` file, I make use of MqttService, imported from "ngx-mqtt" and injected through the constructor. The components works well but not the tests. I have few experience with `.spec.ts` files, but I guess the error might be related with some import or provider that is missing in the test file. I tried adding the `MqttServiceConfig` to the *MoviesComponent.spec.ts* like this:

```javascript
beforeEach(() => {
    fixture = TestBed.configureTestingModule({ imports: [MqttServiceConfig] }).createComponent(MoviesComponent);
    // fixture = TestBed.configureTestingModule({ providers: [MqttService] }).createComponent(MoviesComponent); // <------- Also tried with this
    component = fixture.componentInstance;
    fixture.detectChanges();
});
```

Even this (inspired by [this](https://marina-ferreira.github.io/tutorials/angular5/inject-service-into-component-test/)):

```javascript
it('should create', async(inject([MqttServiceConfig], (myService: MqttServiceConfig) => ...
```

I tried this because **I don't know where to import `NgxMqttServiceConfig` from**. I mean, it is contained inside [MqttModule](https://github.com/sclausen/ngx-mqtt/blob/299e1feac42486f3f46b36d2563ddf2b77c8c715/projects/ngx-mqtt/src/lib/mqtt.module.ts), but it is not exposed. Also tried with `MqttModule` instead of `MqttServiceConfig` with no results. What am I missing?

## Environment
<pre><code>
ngx-mqtt version: 6.13.3
- Broker
Mosquitto
</code></pre>

**Comment by minicatsCB** [comment]
Hello,

I answer myself.

At the end, it was a matter of adding `MqttModule` **along with its configuration** to the TestBed of AppComponent. I was trying adding `MqttModule` alone and in MoviesComponent instead of AppComponent.

My *app.module.ts*:
```javascript
@NgModule({
    declarations: [
        AppComponent,
        MoviesComponent,
        ...
    ],
    imports: [
        BrowserModule,
        HttpClientModule,
        MqttModule.forRoot(AppConstants.MQTT_SERVICE_OPTIONS),
        ...
    ],
    providers: [
        { provide: ErrorHandler, useClass: ErrorHandlerService },
        ...
    ],
    bootstrap: [
        AppComponent
    ]
})
export class AppModule { }
```

My *app.component.spec.ts*:
```javascript
beforeEach(async(() => {
    TestBed.configureTestingModule({
        imports: [
            HttpClientModule,
            MqttModule.forRoot(AppConstants.MQTT_SERVICE_OPTIONS),
            ...
        ],
        providers: [
            { provide: ErrorHandler, useClass: ErrorHandlerService },
            ...
        ]
    }).compileComponents();
}));
```

Where `AppConstants.MQTT_SERVICE_OPTIONS` is a plain object with configuration for `ngx-mqtt`.

Hope this can help somenone. On my side, this issue can be closed. Thank you.
