### ISSUE TITLE
Topic subscription does not work

### ISSUE THREAD

**Issue by ehovaere** [sclausen/ngx-mqtt#79]
- [x] I have searched for similar issues in this repository, but couldn't find one.**
- [x] I have read the README and have a basic understanding how angular works.**

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x ] Bug report  
- [ ] Feature request

## Current behavior
I first created a basic project following the official angular tutorial : https://angular.io/tutorial

I added as in your documentation the necessary lines in app.module.ts and configured the connection like that:

export const MQTT_SERVICE_OPTIONS: IMqttServiceOptions = {
hostname: '192.168.5.55',
port: 10192,
protocol : 'ws',
path: '/mqtt'
};

The connection step seems to work well as because if I change the hostname I get an error in the log console.

Unfortunately, the observe step does not work:
`
@component({
selector: 'app-root',
templateUrl: './app.component.html',
styleUrls: ['./app.component.css']
})
export class AppComponent implements OnDestroy {
title = 'app';
private subscription: Subscription;
public message: string;

constructor(private _mqttService: MqttService) {
console.log('subscribe');
this.subscription = this._mqttService.observe('myTopic').subscribe((message: IMqttMessage) => {
this.message = message.payload.toString();
console.log(this.message);
});
}

...

`

The function will never trigger... whereas another angular app running at the same time using PAHO will log the message.

## Expected behavior
I expected this.message to be updated and the message from mqtt to be displayed in the console

## Environment

<pre><code>
ngx-mqtt version: 5.4.0

- Broker ActiveMQ

Others:

</code></pre>
For my first submitted issue, warning me about the template instead of closing this relatively simple issue would have been nice...

**Comment by sclausen** [comment]
Would you be so kind and post the full code? It's relatively hard to guess what's wrong based on this small snippet. The angular code with paho would also be helpful. have you observed the connection state? Its a field in the service. For convenience, I suggest to put it in a public getter of your component and view it with the async pipe.

Hint: formatting code blocks works with thre backticks ( ` ) followed by the languge (e.g. typescript). After your code block you close the code snippet also with three backticks.

**Comment by ehovaere** [comment]
If I subscribe to the state Observable... I see that it never connects... but I really don't understand why.

**Comment by sclausen** [comment]
I don't know where the extra slash comes from, but I tried with mosquitto and it didn't bothered the mqtt client.
In the end, I'm wrapping MQTT.js, so if your client doesn't, the odds its indeed a bug aren't very high.
Please have a look at [this demo](https://stackblitz.com/edit/ngx-mqtt-demo), try it with your credentials and in `app/app.component.ts#10` and `app/app.component.ts#110` you can see what I meant with the connection state. Would you please look at the console and tell me the output regarding the connection state change?

**Comment by sclausen** [comment]
Does the expression `ParametrageService.mqttSSL == true` evaluate to true?

**Comment by sclausen** [comment]
Maybe you also try removing the leading `/` from the value of the `path` field in the config. Mosquitto doesn't even flinch, but I don't know how ActiveMQ behaves regarding this.

Your issue is really strange. One browser app is working well and the other one isn'n… It has to be a configuration issue, but what's wrong?
Does ActiveMQ logs any errors? You said changing the hostname results in an error, so it **does** try to connect. Otherwise no error would be thrown. Then the second question is: "Why does the client directly disconnect?" If not already done, would you be so kind and [activate debug logging](http://activemq.apache.org/how-do-i-enable-debug-logging.html) in ActiveMQ? I'm curious about what's happening here.

**Comment by ehovaere** [comment]
Hi,

Thanks for that very detailled answer.

yes I tried removing the leading / but the connection then failed because of an invalid host "ws://192.168.5.55:10192mqtt" 

I also tried to add a / on the PAHO side and it works well.

Using the demo you gave me, it does the same as within my project: connecting (1) for a few millisecond and then closed (0).

I added a clientId but it still does not work.

I activated the debug log on broker side and it gave me this: 
```log
2018-05-04 12:00:41,548 | DEBUG | Checkpoint started. | org.apache.activemq.store.kahadb.MessageDatabase | ActiveMQ Journal Checkpoint Worker
2018-05-04 12:00:41,554 | DEBUG | Checkpoint done. | org.apache.activemq.store.kahadb.MessageDatabase | ActiveMQ Journal Checkpoint Worker
2018-05-04 12:00:45,044 | DEBUG | Transport Connection to: ws://192.168.5.55:1625 failed: java.io.IOException | org.apache.activemq.broker.TransportConnection.Transport | qtp1688910949-107
java.io.IOException
	at org.apache.activemq.util.IOExceptionSupport.create(IOExceptionSupport.java:46)[activemq-client-5.14.1.jar:5.14.1]
	at org.apache.activemq.transport.ws.jetty9.MQTTSocket.onWebSocketBinary(MQTTSocket.java:81)[activemq-http-5.14.1.jar:5.14.1]
	at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onBinaryMessage(JettyListenerEventDriver.java:64)[jetty-all-9.2.13.v20150730.jar:9.2.13.v20150730]
	at org.eclipse.jetty.websocket.common.message.SimpleBinaryMessage.messageComplete(SimpleBinaryMessage.java:68)[jetty-all-9.2.13.v20150730.jar:9.2.13.v20150730]
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:64)[jetty-all-9.2.13.v20150730.jar:9.2.13.v20150730]
	at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onBinaryFrame(JettyListenerEventDriver.java:58)[jetty-all-9.2.13.v20150730.jar:9.2.13.v20150730]
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:155)[jetty-all-9.2.13.v20150730.jar:9.2.13.v20150730]
	at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:309)[jetty-all-9.2.13.v20150730.jar:9.2.13.v20150730]
	at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:214)[jetty-all-9.2.13.v20150730.jar:9.2.13.v20150730]
	at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220)[jetty-all-9.2.13.v20150730.jar:9.2.13.v20150730]
	at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:258)[jetty-all-9.2.13.v20150730.jar:9.2.13.v20150730]
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:628)[jetty-all-9.2.13.v20150730.jar:9.2.13.v20150730]
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:476)[jetty-all-9.2.13.v20150730.jar:9.2.13.v20150730]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)[jetty-all-9.2.13.v20150730.jar:9.2.13.v20150730]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)[jetty-all-9.2.13.v20150730.jar:9.2.13.v20150730]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)[jetty-all-9.2.13.v20150730.jar:9.2.13.v20150730]
	at java.lang.Thread.run(Unknown Source)[:1.8.0_161]
2018-05-04 12:00:45,046 | DEBUG | Unregistering MBean org.apache.activemq:type=Broker,brokerName=localhost,connector=clientConnectors,connectorName=mqtt+ws,connectionViewType=remoteAddress,connectionName=ws_//192.168.5.55_1625 | org.apache.activemq.broker.jmx.ManagementContext | qtp1688910949-107
2018-05-04 12:00:45,047 | DEBUG | Stopping connection: ws://192.168.5.55:1625 | org.apache.activemq.broker.TransportConnection | ActiveMQ BrokerService[localhost] Task-43
2018-05-04 12:00:45,048 | DEBUG | Stopped transport: ws://192.168.5.55:1625 | org.apache.activemq.broker.TransportConnection | ActiveMQ BrokerService[localhost] Task-43
2018-05-04 12:00:45,048 | DEBUG | MQTT WebSocket closed: code[1000] message[null] | org.apache.activemq.transport.ws.jetty9.MQTTSocket | qtp1688910949-108
2018-05-04 12:00:45,051 | DEBUG | MQTT Client  disconnecting | org.apache.activemq.transport.mqtt.MQTTProtocolConverter | qtp1688910949-108
2018-05-04 12:00:45,050 | DEBUG | Connection Stopped: ws://192.168.5.55:1625 | org.apache.activemq.broker.TransportConnection | ActiveMQ BrokerService[localhost] Task-43
```

So it seems the broker knows about the client but it fails (crashes) to connect to it...

But no idea how it differs from the paho version...

**Comment by sclausen** [comment]
I didn't meant you to remove both slashes. You said there were two :grin: 

I'm a little disappointed. I thought the missing `clientId: applicationId` in the `IMqttServiceOptions` would have made a difference. 

Could you please try setting `protocolVersion: 3`? I think the default is 4 and maybe ActiveMQ is too old for this s**t :wink: 

If this also doesn't work I'm at my wit's end.

**Comment by sclausen** [comment]
I'm closing this issue, since it is either a bug in MQTT.js or conditioned by the rather antique ActiveMQ.
