### ISSUE TITLE
Angular 6.0 issue

### ISSUE THREAD

**Issue by daneshmandi** [sclausen/ngx-mqtt#80]
## Output Error
<pre><code>
ReferenceError: process is not defined
index.js:3
    at Object../node_modules/process-nextick-args/index.js (d:\Bitbucket\tempdashboard\dashboard.client\node_modules\process-nextick-args\index.js:3:1)
    at __webpack_require__ (http://localhost:4200/runtime.js:82:30)
    at Object../node_modules/readable-stream/lib/_stream_readable.js (d:\Bitbucket\tempdashboard\dashboard.client\node_modules\readable-stream\lib\_stream_readable.js:26:1)
    at __webpack_require__ (http://localhost:4200/runtime.js:82:30)
    at Object../node_modules/readable-stream/readable-browser.js (d:\Bitbucket\tempdashboard\dashboard.client\node_modules\readable-stream\readable-browser.js:1:1)
    at __webpack_require__ (http://localhost:4200/runtime.js:82:30)
    at Object../node_modules/mqtt/lib/store.js (d:\Bitbucket\tempdashboard\dashboard.client\node_modules\mqtt\lib\store.js:8:1)
    at __webpack_require__ (http://localhost:4200/runtime.js:82:30)
    at Object../node_modules/mqtt/lib/client.js (d:\Bitbucket\tempdashboard\dashboard.client\node_modules\mqtt\lib\client.js:7:1)
    at __webpack_require__ (http://localhost:4200/runtime.js:82:30)

</code></pre>

**Comment by sclausen** [comment]
Please use the issue template

**Comment by sclausen** [comment]
I'm amazed that you think simply posting an error message without any further information will help solving this issue.
If you don't want to invest in this and fill out the issue template I'm not willing to invest my spare time.

**Comment by daneshmandi** [comment]
@sclausen I am sorry for that. I will repost using the template.
